#!/usr/bin/env node

const fs = require('fs');
const D3Node = require('d3-node');
const d3 = require('d3');
const path = require("path");
const yargs = require('yargs');

const argv = yargs
    .usage(`rendermup input.mup`)
    .demand(1)
    .option("w", {
        alias: "width",
        type: "number",
        describe: "The output file width, in pixels",
        default: "1260"
    })
    .option("h", {
        alias: "height",
        type: "number",
        describe: "The output file height, in pixels",
        default: "-1"
    })
    .option("r", {
        alias: "right-justified",
        type: "boolean",
        describe: "render the tree with all leaves at the right (i.e. cluster/dendrogram layout)",
        default: "false"
    })
    .help(false)
    .argv;

const input = fs.readFileSync(argv._[0], 'utf8');
const outputHtmlFilename = path.basename(argv._[0], ".mup") + ".html";
const outputSvgFilename = path.basename(argv._[0], ".mup") + ".svg";
const outputPngFilename = path.basename(argv._[0], ".mup") + ".png";

const styles = `

.node circle {
  fill: #999;
}

.node text {
  font: 10px sans-serif;
}

.node--leaf_oos text {
  text-decoration: line-through;
}

.node--internal circle {
  stroke: #d3d3d3;
  fill: #FFF;
}

.node--leaf circle {
  fill: #000;
}

.node--leaf_ref circle {
  stroke: #000;
  fill: #FFF;
}

.node--leaf_oos circle {
  fill: #000;
}

.link {
  fill: none;
  stroke: #d3d3d3;
  stroke-opacity: 1.0;
  stroke-width: 1.5px;
}

`;
const markup = '<meta http-equiv="refresh" content="3" ><div id="container"><div id="chart"></div></div>';
var options = {selector:'#chart', svgStyles:styles, container:markup, d3Module:d3};

var d3n = new D3Node(options);

///-- start D3 code
do_draw = function(json) {
  var root_node = d3.hierarchy(json, function(d) {
    if (typeof d.ideas === "undefined"){ return null; }
    if (typeof d.attr !== "undefined" && typeof d.attr.collapsed !== "undefined" && d.attr.collapsed === true) { return null; }
    //sort(...) orders the ideas the same as the children are ordered in mindmup
    return Object.keys(d.ideas).sort(function(a,b) { return a - b; }).map(key => d.ideas[key]);
  });

  //Wow, this is embarassing. Please look away!
  // 'works' only for 10pt sans-serif, here, when stars are properly aligned
  var approxTextWidth = (function() {
      function charW(w, c) {
          if (c == 'W' || c == 'M') w += 15;
          else if (c == 'w' || c == 'm') w += 12;
          else if (c == 'I' || c == 'i' || c == 'l' || c == 't' || c == 'f') w += 4;
          else if (c == 'r') w += 8;
          else if (c == c.toUpperCase()) w += 12;
          else w += 10;
          return w;
      }

      return function(s) {
          return s.split('').reduce(charW, 0) / 2;
      };
  })();

  var margin = {top: 10, right: 24, bottom: 4, left: 40};

  var text_line_height = 10 * 1.1;
  var node_width_size;
  var node_height_size;
  if (argv.width !== -1 && argv.height == -1) {
    max_depth = 0;
    root_node.each(function(d){
      max_depth = Math.max(max_depth, d.depth);
    });
    available_text_width = Math.floor((argv.width - margin.left - margin.right) / (max_depth+1));
    node_width_size = available_text_width;

    max_text_height = 0;
    root_node.each(function(d){
      if (argv.r && typeof d.children !== 'undefined') return;

      approx_height = Math.ceil(approxTextWidth(d.data.title) / available_text_width) * text_line_height;
      max_text_height = Math.max(max_text_height, approx_height);
    });
    node_height_size = max_text_height;

    if (argv.r) {
      node_height_size = node_height_size * 1.2;
    }
  }

  var svg = d3n.createSVG();

  width = argv.width - margin.left - margin.right;

  var tree_maker;
  if (argv.r) {
    //dendrograms
    tree_maker = d3.cluster();
  }
  else {
    tree_maker = d3.tree();
  }

  function is_freeheight_layout() { return argv.height == -1 && !argv.r; }

  var tree;
  if (is_freeheight_layout()) {
    tree = tree_maker.nodeSize([node_height_size, node_width_size]); //TODO why's all my stuff rotated 90deg?
  } else {
    var height;
    if (argv.r) {
      leaf_count = 0;
      root_node.each(function(d){
        if (typeof d.children !== 'undefined') return;

        leaf_count = leaf_count + 1;
      });

      height = (node_height_size + text_line_height) * leaf_count + 1 * text_line_height;
    } else {
      height = argv.height - margin.top - margin.bottom;
    }
    tree = tree_maker.size([height, width - node_width_size / 2 - margin.right]);
  }

  var tree_data = tree(root_node).descendants().slice(1);

  // For freeheight layouts, translate to keep all nodes in-view
  if (true) {
    var min_x = Number.MAX_SAFE_INTEGER;
    root_node.each(function(d){
      min_x = Math.min(min_x, d.x);
    });

    root_node.each(function(d){
      d.x = d.x - min_x;
    });
  }

  // calculate the overall height
  max_x = 0;
  root_node.each(function(d){
    max_x = Math.max(max_x, d.x);
  });

  height = max_x + node_height_size;
  total_width = width + margin.left + margin.right;
  total_height = height + margin.top + margin.bottom;

  var g = svg
    .attr("width", total_width)
    .attr("height", total_height)
    .attr("viewBox", "0 0 " + total_width + " " + total_height)
    .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

  var text_wrap_width = Number.MAX_SAFE_INTEGER;
  root_node.each(function(d){
    if (d.parent === null) return;

    text_wrap_width = Math.min(text_wrap_width, d.y - d.parent.y);
  });
  text_wrap_width = 0.9 * text_wrap_width;

  // In a dendrogram, give the leaf nodes more room -- but do it after sizing to *compensate* for the d3 rendering, not influence it.
  if (argv.r) {
    root_node.each(function(d){
      if (typeof d.children === 'undefined') {
        d.y = d.y - node_width_size / 2;
      }
    });
  }

  // In a dendrogram, bump the next sibling of blocks with looooong text
  if (argv.r) {
    root_node.each(function(d){
      if (typeof d.children !== 'undefined') return;
      if (d.parent === null) return;

      text_line_count = Math.ceil(approxTextWidth(d.data.title) / text_wrap_width);
      text_height = text_line_height * text_line_count;

      d.parent.children.forEach(function(child){
        if (child.x > d.x && child.x < d.x + text_height) {
          child.x = child.x + text_line_height;
        }
      });
    });
  }

  var link = g.selectAll(".link")
    .data(tree_data)
    .enter().append("path")
      .attr("class", "link")
      .attr("d", function(d) {
        elbow_point = (d.parent.y + 9*(d.y - d.parent.y) / 10)

        if (argv.r) {
          elbow_point = d.parent.y;
          if (d.parent.parent === null) {
            var min_y = d.y;
            d.parent.children.forEach(function(entry){
              min_y = Math.min(min_y, entry.y);
            })
            elbow_point = (d.parent.y + (min_y - d.parent.y) / 2)
          }
        }

        return "M" + d.parent.y + "," + d.parent.x
            + "H" + elbow_point + "V" + d.x + "H" + d.y;
      });

  function d3TextWrap(text, width) {
      var arrLineCreatedCount = [];
      text.each(function() {
          var text = d3.select(this),
              words = text.text().split(/[ \f\n\r\t\v]+/).reverse(), //Don't cut non-breaking space (\xA0), as well as the Unicode characters \u00A0 \u2028 \u2029)
              word,
              line = [],
              lineNumber = 0,
              lineHeight = 1.05, //Ems
              x = text.attr("x"),
              y = text.attr("y"),
              createdLineCount = 1; //Total line created count
          var textAlign = text.style('text-anchor') || 'left';
          var alignmentBase = text.style('alignment-baseline') || 'baseline';
          var adjusted_width = width;
          if (text.datum().parent === null) {
            adjusted_width = width/2 + margin.left;
          }

          dy = 0;
          x = 0;
          if (textAlign === 'start') {
            x = 8;
          }
          if (text.datum().parent === null) {
            x = x - margin.left;
          }

          y = 3;
          if (alignmentBase === 'hanging') {
            y = 12;
          } else if (alignmentBase === 'ideographic') {
            y = -6;
          }

          var tspan = text.text(null).append("tspan").attr("x", x).attr("y", y).attr("dy", dy + "em");
          //noinspection JSHint
          while (word = words.pop()) {
              line.push(word);
              tspan.text(line.join(" "));
              if (approxTextWidth(line.join(" ")) > adjusted_width && line.length > 1) {
                  line.pop();
                  tspan.text(line.join(" "));
                  line = [word];
                  tspan = text.append("tspan").attr("x", x).attr("y", y).attr("dy", ++lineNumber * lineHeight + dy + "em").text(word); //TODO: don't use dy -- it is making glitches in jsdom; instead increment by 1.1* font size in px (assume 10 for now)
                  ++createdLineCount;
              }
          }

          arrLineCreatedCount.push(createdLineCount); //Store the line count in the array
      });
      return arrLineCreatedCount;
  }

  function get_raw_description(d) {
    var description = ((d.data.attr || {}).note || {}).text || '';
    if (description === '') {
      description = ((d.data.attr || {}).attachment || {}).content || ''
    }

    return description;
  }

  function get_title(d) {
    return d.data.title || '';
  }

  function is_leaf(d) {
    return typeof d.children === 'undefined';
  }

  function is_reference(d) {
    return ( get_title(d).search("\\(\\*\\)") !== -1  ) || (/\(\d+\..*?\)/.test(get_title(d)));
  }

  function is_out_of_scope(d) {
    return /out of scope/i.test(get_raw_description(d));
  }

  var node = g.selectAll(".node")
    .data(root_node.descendants())
    .enter().append("g")
      .attr("class", function(d) {
        if (typeof d.children === 'undefined') {
          if (is_reference(d)) {
            return "node node--leaf_ref";
          } else if (is_out_of_scope(d)) {
            return "node node--leaf_oos";
          } else {
            return "node node--leaf";
          }
        } else {
          return "node node--internal";
        }
        return "node" + (d.children ? " node--internal" : " node--leaf"); 
      })
      .attr("transform", function(d) { return "translate(" + d.y + "," + d.x + ")"; })

  node.append("circle")
      .attr("r", 2.5);

  node.append("text")
      .attr("dy", 3)
      .attr("x", function(d) { return d.children ? -8 : 8; })
      .style("text-anchor", function(d) {
          if (d.parent === null) {
            return "start";
          }
          return d.children ? "middle" : "start";
      })
      .style("alignment-baseline", function(d) {
          if (d.data.title === "AND") {
            return "middle";
          }
          if (d.parent === null) {
            return "ideographic";
          }
          return d.children ? "hanging" : "baseline";
      })
      .text(function(d) { return d.data.title; })
      .call(d3TextWrap, text_wrap_width, 0, 0);
};

mindmup_json = JSON.parse(input);

if (typeof mindmup_json.id !== "undefined" && mindmup_json['id'] === "root") { // handle >= 2 mindmup_json
  mindmup_json = mindmup_json['ideas']['1'];
}

do_draw(mindmup_json);

/// -- end D3 code

// create output files
const svg2png = require('svg2png');

fs.writeFile(outputHtmlFilename, d3n.html(), function () {
  console.log('>> Done. Open '+outputHtmlFilename+'" in a web browser');
});

var svg_string = d3n.svgString();
fs.writeFile(outputSvgFilename, svg_string, function () {
  console.log('>> Exported: "'+outputSvgFilename+'"');
});

var svgBuffer = new Buffer(svg_string, 'utf-8');
svg2png(svgBuffer, {width: width*4})
  .then(buffer => fs.writeFile(outputPngFilename, buffer))
  .catch(e => console.error('ERR:', e))
  .then(err => console.log('>> Exported: "'+outputPngFilename+'"'));

