#!/usr/bin/env python

import sys,json
from mindmup_as_attack_trees import *

def fix_titles(root):
	def title_strip(node):
		title = get_node_title(node)

		if title is '':
			return

		title = re.sub(r'\n+', ' ', title)
		title = re.sub(r'\s+$', '', title)

		set_node_title(node, title)
		return

	apply_each_node(root, title_strip)
	return

if len(sys.argv) < 2:
	fd_in=sys.stdin
else:
	fd_in=open(sys.argv[1], 'r')

data = json.load(fd_in)

if len(sys.argv) < 2:
	fd_out = sys.stdout
else:
	fd_in.close()
	fd_out=open(sys.argv[1],'w')

if 'id' in data and data['id'] == 'root':
	#version 2 mindmup
	root_node = data['ideas']['1']
else:
	root_node = data

fix_titles(root_node)

str = json.dumps(data, indent=2, sort_keys=True)
str = re.sub(r'\s+$', '', str, 0, re.M)
str = re.sub(r'\s+$', '', str, flags=re.M)

fd_out.write(str)

if len(sys.argv) >= 1:
	fd_out.close()

